package cn.edu.bupt.wen.model;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.math
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    private Integer math;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.chinese
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    private Integer chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.english
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    private Integer english;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.math
     *
     * @return the value of score.math
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public Integer getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.math
     *
     * @param math the value for score.math
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public void setMath(Integer math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.chinese
     *
     * @return the value of score.chinese
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public Integer getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.chinese
     *
     * @param chinese the value for score.chinese
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public void setChinese(Integer chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.english
     *
     * @return the value of score.english
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public Integer getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.english
     *
     * @param english the value for score.english
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    public void setEnglish(Integer english) {
        this.english = english;
    }
}