package cn.edu.bupt.wen.mapper;

import cn.edu.bupt.wen.model.Sys_permissions;
import cn.edu.bupt.wen.model.Sys_permissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_permissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int countByExample(Sys_permissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int deleteByExample(Sys_permissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int insert(Sys_permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int insertSelective(Sys_permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    List<Sys_permissions> selectByExample(Sys_permissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    Sys_permissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sys_permissions record, @Param("example") Sys_permissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int updateByExample(@Param("record") Sys_permissions record, @Param("example") Sys_permissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int updateByPrimaryKeySelective(Sys_permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated Mon Sep 18 13:05:50 CST 2017
     */
    int updateByPrimaryKey(Sys_permissions record);
}